package hdar.algorithm;

import static org.assertj.core.api.Assertions.assertThat;

import org.jsoup.Jsoup;
import org.junit.Test;

import hdar.model.HdaEntry;

public class HdaEntryParserTest {
	private static String testWebSite = "\r\n" + "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\r\n"
			+ "    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
			+ "<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n" + "<head>\r\n" + " \r\n"
			+ "<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"/>\r\n"
			+ "<meta name=\"description\" content=\"HD-Filme zum kostenlosen Download auf verschiedenen One-Klick-Hostern wie Rapidshare.com, Netload.in und Share-Online.biz\"/>\r\n"
			+ "<meta name=\"keywords\" content=\"high definition, hd, 1080p, 720p, download, rapidshare.com, rapidshare, netload, free, kostenlos\"/>\r\n"
			+ "<meta name=\"author\" content=\"Ak.Tronic\"/>\r\n"
			+ "<meta name=\"generator\" content=\"HD-Area CMS\"/>\r\n"
			+ "<meta name=\"Copyright\" content=\"Copyright (c) 2010 HD-Area.org\"/>\r\n"
			+ "<meta name=\"revisit-after\" content=\"1 Days\"/>\r\n" + " \r\n"
			+ "<link rel=\"alternate\" type=\"application/rss+xml\" title=\"HD-Area RSS-Feed\" href=\"http://hd-area.org/?s=feedrss\"/>\r\n"
			+ "<link rel=\"alternate\" type=\"application/atom+xml\" title=\"HD-Area Atom-Feed\" href=\"http://hd-area.org/?s=feedrss\"/>\r\n"
			+ " \r\n" + "<link rel=\"stylesheet\" href=\"css.css\" type=\"text/css\" media=\"screen\"/>\r\n" + " \r\n"
			+ "<title>HD-Area.org: How.to.Get.Away.with.Murder.S01.GERMAN.720p.HDTV.x264-MDGP</title>\r\n"
			+ "</head>\r\n" + "<body>\r\n" + " \r\n"
			+ "<div id=\"header\"><img src=\"http://hd-area.org/grafik/hdaheader.png\" alt=\"HD-Area.org Header\"/></div>\r\n"
			+ " \r\n"
			+ "<div id=\"navigation\"><a href=\"index.php\" title=\"Home\"><img src=\"http://img.hd-area.org/grafik/home.gif\" title=\"Home\" alt=\"Home\"/></a>\r\n"
			+ "<a href=\"?s=top-rls\" title=\"Top Releases\"><img src=\"http://img.hd-area.org/grafik/topreleasesneu.gif\" title=\"Top Releases\" alt=\"Top Releases\"/></a>\r\n"
			+ "<a href=\"?s=cinedubs\" title=\"Cinedubs\"><img src=\"http://img.hd-area.org/grafik/cinedubs.gif.png\" title=\"Cinedubs\" alt=\"Cinedubs\"/></a>\r\n"
			+ "<a href=\"?s=3D\" title=\"3D Filme\"><img src=\"http://img.hd-area.org/grafik/3d-filme.png\" title=\"3D Filme\" alt=\"3D Filme\"/></a>\r\n"
			+ "<a href=\"index.php?s=XXX\" title=\"XXX\"><img src=\"http://img.hd-area.org/grafik/xxx.gif\" title=\"XXX\" alt=\"XXX\"/></a>\r\n"
			+ "<a href=\"altsearch.php\"><img alt=\"Archiv\" src=\"http://img.hd-area.org/grafik/archiv.gif\"/></a>\r\n"
			+ "<a href=\"?s=faq\" title=\"FAQ\"><img src=\"http://img.hd-area.org/grafik/faq.gif\" title=\"FAQ\" alt=\"FAQ\"/></a>\r\n"
			+ "<a href=\"http://board.hd-area.org/\" title=\"Board\"><img src=\"http://img.hd-area.org/grafik/board.gif\" title=\"Board\" alt=\"Board\"/></a></div>\r\n"
			+ " \r\n" + "<div id=\"container\">\r\n" + " \r\n" + "<div id=\"subcontent\">\r\n" + " \r\n"
			+ "<div id=\"suche\">&nbsp;</div>\r\n"
			+ "<div class=\"suchen\"><form method=\"get\" action=\"http://www.hd-area.org/\">\r\n"
			+ "<input type=\"hidden\" value=\"search\" name=\"s\"/>\r\n"
			+ "<p class=\"search_input\"><input type=\"text\" value=\"\" name=\"q\" size=\"23\"/><input type=\"submit\" value=\"Suche\"/></p>\r\n"
			+ "</form>\r\n" + "<br/>\r\n" + "</div>\r\n" + " \r\n" + "<div class=\"info\">&nbsp;</div>\r\n"
			+ "<div class=\"rightbox\"><center>\r\n" + "<b>new backup domain: hd-area.biz</b><br><br>\r\n"
			+ "<b>Unterstützt uns und nutzt Share-Online..</b><br>\r\n" + "<br>\r\n"
			+ "<img src=\"http://img.share-online.biz/fs06021d.gif\"><br>\r\n"
			+ "<br><b>oder spendet per Bitcoin <br><br></b>\r\n" + "<br>\r\n"
			+ "<img src=\"http://e-pic.biz/img/uPdJSlL1K9DxcCQ.jpg\"><br><br>\r\n"
			+ "<b><a href=\"wallet.html\">Unsere Walletadresse (klick)</a></b>\r\n" + "<br>\r\n" + "<br>\r\n"
			+ "<b>Filmwünsche für die <a href=\"http://www.hd-area.org/index.php?s=Old_Stuff\">Old Stuff Sektion</a> können im <a href=\"http://board.hd-area.org/viewforum.php?f=54\">Forum</a> abgegeben werden.<br><br>\r\n"
			+ "<b>Sucht Filme <span style=\"color: #993300;\">im Archiv</span>. Dort wird alles aufgelistet. Auch die \"Old Stuff\" Sektion</b>\r\n"
			+ "<br/>\r\n"
			+ "<center><img border=\"0\" alt=\"Wir Speichern Nicht\" src=\"http://e-pic.biz/img/21B36dqpCFr0HEJ.png\"/>\r\n"
			+ "</center><br/>\r\n" + "<center><br><p>\r\n" + "<br><br>\r\n" + "</b>\r\n" + "</p></center>\r\n"
			+ "</div>\r\n" + " \r\n" + "<div id=\"kat\">&nbsp;</div>\r\n"
			+ "<div class=\"rightbox\"><div id=\"menutree\">\r\n" + "<ul>\r\n" + "<li>\r\n"
			+ "<a href=\"index.php?c=Film-Formate\">Film-Formate</a>\r\n" + "<ul>\r\n"
			+ "<li><a href=\"index.php?c=720p\">720p</a></li>\r\n"
			+ "<li><a href=\"index.php?c=1080i\">1080i</a></li>\r\n"
			+ "<li><a href=\"index.php?c=1080p\">1080p</a></li>\r\n"
			+ "<li><a href=\"index.php?c=BluRay-Untouched\">BluRay Untouched</a></li>\r\n"
			+ "<li><a href=\"index.php?c=BluRay-Remux\">BluRay Remux</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Serien-Untouched\">Serien Untouched</a></li>\r\n"
			+ "<li><a href=\"index.php?c=4k-uhd-untouched\">4k UHD untouched</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Stream-Untouched\">Stream Untouched</a></li>\r\n" + "</ul>\r\n" + "</li>\r\n"
			+ "<li><a href=\"index.php?c=Filme\">Filme</a><ul>\r\n"
			+ "<li><a href=\"index.php?c=Abenteuer\">Abenteuer</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Action\">Action</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Animationsfilm\">Animationsfilm</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Anime\">Anime</a></li>\r\n"
			+ "<li><a href=\"index.php?c=anime-japanische-tonspur\">Anime japanische Tonspur</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Biografie\">Biografie</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Bollywood\">Bollywood</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Dokumentation\">Dokumentation</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Drama\">Drama</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Endzeit\">Endzeit</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Erotik\">Erotik</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Familienfilm\">Familienfilm</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Fantasy\">Fantasy</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Fremdsprachige-Filme\">Fremdsprachige Filme</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Historienfilm\">Historienfilm</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Horror\">Horror</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Komoedie\">Komödie</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Kinderfilm\">Kinderfilm</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Kriegsfilm\">Kriegsfilm</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Krimi\">Krimi</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Liebesfilm\">Liebesfilm</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Musik-Konzerte\">Musik (Konzerte)</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Musikvideo\">Musikvideo</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Musical\">Musical</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Mysterie\">Mysterie</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Musikfilm\">Musikfilm</a></li>\r\n"
			+ "<li><a href=\"index.php?c=oper-operette\">Oper / Operette</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Science-Fiction\">Science Fiction</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Spezial\">Spezial</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Sport\">Sport</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Thriller\">Thriller</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Western\">Western</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Zeichentrick\">Zeichentrick</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Verschiedenes\">Verschiedenes</a></li>\r\n"
			+ "<li><a href=\"index.php?c=X-Mas\">X-Mas</a></li>\r\n" + "</ul>\r\n" + "</li>\r\n"
			+ "<li><a href=\"index.php?c=Serien\">Serien</a>\r\n" + "<ul>\r\n"
			+ "<li><a href=\"index.php?c=taegliches-serienpaket\">taegliches Serienpaket</a></li>\r\n"
			+ "<li><a href=\"index.php?c=2-broke-girls\">2 Broke Girls</a></li>\r\n"
			+ "<li><a href=\"index.php?c=24\">24</a></li>\r\n"
			+ "<li><a href=\"index.php?c=30-Rock\">30 Rock</a></li>\r\n"
			+ "<li><a href=\"index.php?c=airwolf\">Airwolf</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Alcatraz\">Alcatraz</a></li>\r\n"
			+ "<li><a href=\"index.php?c=american-dad\">American Dad</a></li>\r\n"
			+ "<li><a href=\"index.php?c=American-Horror-Story\">American Horror Story</a></li>\r\n"
			+ "<li><a href=\"index.php?c=arrow\">Arrow</a></li>\r\n"
			+ "<li><a href=\"index.php?c=atlantis\">Atlantis</a></li>\r\n"
			+ "<li><a href=\"index.php?c=bates-motel\">Bates Motel</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Battlestar-Galactica\">Battlestar Galactica</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Band-of-Brothers\">Band of Brothers</a></li>\r\n"
			+ "<li><a href=\"index.php?c=banshee-small-town-big-secrets\">Banshee Small Town Big Secrets</a></li>\r\n"
			+ "<li><a href=\"index.php?c=being-human\">Being Human</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Bones\">Bones</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Breaking-Bad\">Breaking Bad</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Burn-Notice\">Burn Notice</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Californication\">Californication</a></li>\r\n"
			+ "<li><a href=\"index.php?c=chicago-fire\">Chicago Fire</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Criminal-Minds\">Criminal Minds</a></li>\r\n"
			+ "<li><a href=\"index.php?c=crossing-jordan\">Crossing Jordan</a></li>\r\n"
			+ "<li><a href=\"index.php?c=crossing-lines\">Crossing Lines</a></li>\r\n"
			+ "<li><a href=\"index.php?c=castle\">Castle</a></li>\r\n"
			+ "<li><a href=\"index.php?c=CSI\">CSI</a></li>\r\n"
			+ "<li><a href=\"index.php?c=continuum\">Continuum</a></li>\r\n"
			+ "<li><a href=\"index.php?c=da-vincis-demons\">Da Vincis Demons</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Damages\">Damages</a></li>\r\n"
			+ "<li><a href=\"index.php?c=defiance\">Defiance</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Desperate-Housewives\">Desperate Housewives</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Dexter\">Dexter</a></li>\r\n"
			+ "<li><a href=\"index.php?c=die-drachenreiter-von-berk\">Die Drachenreiter von Berk</a></li>\r\n"
			+ "<li><a href=\"index.php?c=die-legende-von-korra\">Die Legende von Korra</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Die-Simpsons\">Die Simpsons</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Die-Tudors\">Die Tudors</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Die-wilden-70er\">Die wilden 70er</a></li>\r\n"
			+ "<li><a href=\"index.php?c=doctor-who\">Doctor Who</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Dr-House\">Dr. House</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Eureka\">Eureka</a></li>\r\n"
			+ "<li><a href=\"index.php?c=extant\">Extant</a></li>\r\n"
			+ "<li><a href=\"index.php?c=falling-skies\">Falling Skies</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Fargo\">Fargo</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Fringe\">Fringe</a></li>\r\n"
			+ "<li><a href=\"index.php?c=game-of-thrones\">Game of Thrones</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Glee\">Glee</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Gossip-Girl\">Gossip Girl</a></li>\r\n"
			+ "<li><a href=\"index.php?c=gotham\">Gotham</a></li>\r\n"
			+ "<li><a href=\"index.php?c=grimm\">Grimm</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Hannibal\">Hannibal</a></li>\r\n"
			+ "<li><a href=\"index.php?c=hell-on-wheels\">Hell on Wheels</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Heroes\">Heroes</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Homeland\">Homeland</a></li>\r\n"
			+ "<li><a href=\"index.php?c=house-of-cards\">House of Cards</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Hunted\">Hunted</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Jericho\">Jericho</a></li>\r\n"
			+ "<li><a href=\"index.php?c=kommissarin-lund\">Kommissarin Lund</a></li>\r\n"
			+ "<li><a href=\"index.php?c=law-and-order\">Law and Order</a></li>\r\n"
			+ "<li><a href=\"index.php?c=letzte-spur-berlin\">Letzte Spur Berlin</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Lost\">Lost</a></li>\r\n"
			+ "<li><a href=\"index.php?c=marvels-agent-carter\">Marvels Agent Carter</a></li>\r\n"
			+ "<li><a href=\"index.php?c=marvelsagentsofshield\">Marvels.Agents.of.S.H.I.E.L.D</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Masters-of-Sex\">Masters of Sex</a></li>\r\n"
			+ "<li><a href=\"index.php?c=modern-family\">Modern Family</a></li>\r\n"
			+ "<li><a href=\"index.php?c=my-little-pony\">My little Ponyl</a></li>\r\n"
			+ "<li><a href=\"index.php?c=My-Name-is-Earl\">My Name is Earl</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Psych\">My Psych</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Navy-CIS\">Navy C.I.S.</a></li>\r\n"
			+ "<li><a href=\"index.php?c=new-girl\">New Girl</a></li>\r\n"
			+ "<li><a href=\"index.php?c=OCCalifornia\">O.C.California</a></li>\r\n"
			+ "<li><a href=\"index.php?c=orange-is-the-new-black\">Orange is the New Black</a></li>\r\n"
			+ "<li><a href=\"index.php?c=outlander\">Outlander</a></li>\r\n"
			+ "<li><a href=\"index.php?c=penny-dreadful\">Penny Dreadful</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Person-of-Interest\">Person of Interest</a></li>\r\n"
			+ "<li><a href=\"index.php?c=ray-donovan\">Ray Donovan</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Rom\">Rom</a></li>\r\n"
			+ "<li><a href=\"index.php?c=revolution\">Revolution</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Secret-Diary-of-a-call-Girl\">Secret Diary of a Call Girl</a></li>\r\n"
			+ "<li><a href=\"index.php?c=shameless\">Shameless</a></li>\r\n"
			+ "<li><a href=\"index.php?c=sherlock\">Sherlock</a></li>\r\n"
			+ "<li><a href=\"index.php?c=sleepy-hollow\">Sleepy Hollow</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Smallville\">Smallville</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Sons-of-Anarchy\">Sons of Anarchy</a></li>\r\n"
			+ "<li><a href=\"index.php?c=south-park\">South Park</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Star-Trek-Enterprise\">Star Trek Enterprise</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Star-Trek-TOS\">Star Trek TOS</a></li>\r\n"
			+ "<li><a href=\"index.php?c=star-wars-the-clone-wars\">Star Wars The Clone Wars</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Stargate-Atlantis\">Stargate Atlantis</a></li>\r\n"
			+ "<li><a href=\"index.php?c=stargate-sg-1\">Stargate SG 1</a></li>\r\n"
			+ "<li><a href=\"index.php?c=star-wars-rebels\">Star Wars Rebels</a></li>\r\n"
			+ "<li><a href=\"index.php?c=strike-back\">Strike Back</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Supernatural\">Supernatural</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Tatort\">Tatort</a></li>\r\n"
			+ "<li><a href=\"index.php?c=the-100\">The 100</a></li>\r\n"
			+ "<li><a href=\"index.php?c=The-Big-Bang-Theory\">The Big Bang Theory</a></li>\r\n"
			+ "<li><a href=\"index.php?c=The-Blacklist\">The Blacklist</a></li>\r\n"
			+ "<li><a href=\"index.php?c=the-flash\">The Flash</a></li>\r\n"
			+ "<li><a href=\"index.php?c=the-good-wife\">The good Wife</a></li>\r\n"
			+ "<li><a href=\"index.php?c=The-Killing\">The Killing</a></li>\r\n"
			+ "<li><a href=\"index.php?c=The-last-Ship\">The last Ship</a></li>\r\n"
			+ "<li><a href=\"index.php?c=the-quest\">The Quest</a></li>\r\n"
			+ "<li><a href=\"index.php?c=The-Mentalists\">The Mentalist</a></li>\r\n"
			+ "<li><a href=\"index.php?c=the-originals\">The Originals</a></li>\r\n"
			+ "<li><a href=\"index.php?c=The-Sarah-Connor-Chronicals\">The Sarah Connor Chronicals</a></li>\r\n"
			+ "<li><a href=\"index.php?c=The-Walking-Dead\">The Walking Dead</a></li>\r\n"
			+ "<li><a href=\"index.php?c=The-Vampire-Diaries\">The Vampire Diaries</a></li>\r\n"
			+ "<li><a href=\"index.php?c=True-Blood\">True Blood</a></li>\r\n"
			+ "<li><a href=\"index.php?c=True-Detective\">True Detective</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Two-and-a-half-Men\">Two and a half Men</a></li>\r\n"
			+ "<li><a href=\"index.php?c=undercover\">Undercover</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Under-the-Dome\">Under the Dome</a></li>\r\n"
			+ "<li><a href=\"index.php?c=vikings\">Vikings</a></li>\r\n"
			+ "<li><a href=\"index.php?c=Weeds\">Weeds</a></li>\r\n" + "</ul>\r\n" + "</li>\r\n"
			+ "<li><a href=\"index.php?s=Musik\">Musik</a><ul>\r\n"
			+ "<li><a href=\"index.php?s=Musik&amp;c=blu-ray-audio\">Blu-ray Audio</a></li>\r\n"
			+ "<li><a href=\"index.php?s=Musik&amp;c=Chillout\">Chillout</a></li>\r\n" + "</li>\r\n"
			+ "<li><a href=\"index.php?s=Musik&amp;c=Folk\">Folk</a></li>\r\n"
			+ "<li><a href=\"index.php?s=Musik&amp;c=Formate\">Formate</a><ul>\r\n"
			+ "<li><a href=\"index.php?c=Audiophile\">Audiophile</a></li>\r\n"
			+ "<li><a href=\"index.php?s=Musik&amp;c=Musik-DVD\">Musik-DVD</a></li>\r\n" + "</ul>\r\n" + "</li>\r\n"
			+ "<li><a href=\"index.php?s=Musik&amp;c=klassik\">Klassik</a></li>\r\n"
			+ "<li><a href=\"index.php?s=Musik&amp;c=Metal\">Metal</a></li>\r\n"
			+ "<li><a href=\"index.php?s=Musik&amp;c=Rock\">Rock</a></li>\r\n"
			+ "<li><a href=\"index.php?s=Musik&amp;c=sacd\">SACD</a></li>\r\n"
			+ "<li><a href=\"index.php?s=Musik&amp;c=Verschiedenes\">Verschiedenes</a></li>\r\n" + "</ul></li>\r\n"
			+ "<li><a href=\"index.php?s=XXX\">XXX</a><ul>\r\n"
			+ "<li><a href=\"index.php?s=XXX&amp;c=3D-Porn\">3D Porn</a></li>\r\n"
			+ "<li><a href=\"index.php?s=XXX&amp;c=4k-Porn\">4k Porn</a></li>\r\n"
			+ "<li><a href=\"index.php?s=XXX&amp;c=Asian-JAV\">Asian/JAV</a></li>\r\n"
			+ "<li><a href=\"index.php?s=XXX&amp;c=imagesets\">Imagesets</a></li>\r\n"
			+ "<li><a href=\"index.php?s=XXX&amp;c=Filme-720p\">720p Movies</a></li>\r\n"
			+ "<li><a href=\"index.php?s=XXX&amp;c=720p-Clips\">720p Clips</a></li>\r\n"
			+ "<li><a href=\"index.php?s=XXX&amp;c=1080p-Movies\">1080p Movies</a></li>\r\n"
			+ "<li><a href=\"index.php?s=XXX&amp;c=Untouched-XXX\">Untouched XXX</a></li>\r\n"
			+ "<li><a href=\"index.php?s=XXX&amp;c=1080p-Clips\">1080p Clips</a></li>\r\n"
			+ "<li><a href=\"index.php?s=XXX&amp;c=1080i-Clips\">1080i Clips</a></li>\r\n" + "</ul></li>\r\n"
			+ "</ul>\r\n" + "</div></div>\r\n" + "<div class=\"subbottom\">&nbsp;</div>\r\n" + "</div>\r\n" + " \r\n"
			+ " \r\n" + "<div id=\"subcontent2\" class=\"nowrap\">\r\n" + " \r\n"
			+ "<div id=\"aktuell\">&nbsp;</div>\r\n"
			+ "<div class=\"rightbox\"><span><a href=\"index.php?s=top-rls\"><strong class=\"main\">Top Releases</strong></a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101155\" title=\"Dealer.2014.DUAL.COMPLETE.BLURAY-GMB\">Dealer.2014.DUAL.COMPLETE.BL...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101128\" title=\"God.Loves.the.Fighter.2015.German.1080p.DL.DTSHD.BluRay.AVC.Remux-pmHD\">God.Loves.the.Fighter.2015.G...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101091\" title=\"Cartel.Land.2015.German.1080p.DTSHD.BluRay.AVC.Remux-pmHD\">Cartel.Land.2015.German.1080...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101080\" title=\"God.Loves.the.Fighter.2013.MULTI.COMPLETE.BLURAY-FORBiDDEN\">God.Loves.the.Fighter.2013.M...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101042\" title=\"Cartel.Land.2015.DUAL.COMPLETE.BLURAY-ROOR\">Cartel.Land.2015.DUAL.COMPLE...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101028\" title=\"God.Loves.the.Fighter.2013.German.DL.1080p.BluRay.x264-ROOR\">God.Loves.the.Fighter.2013.G...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101027\" title=\"God.Loves.the.Fighter.2013.German.720p.BluRay.x264-ROOR​\">God.Loves.the.Fighter.2013.G...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101022\" title=\"Cartel.Land.2015.German.1080p.BluRay.x264-ROOR\">Cartel.Land.2015.German.1080...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101023\" title=\"Cartel.Land.2015.German.720p.BluRay.x264-ROOR\">Cartel.Land.2015.German.720p...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101015\" title=\"Winnetous.Sohn.2015.German.COMPLETE.BLURAY-GMB\">Winnetous.Sohn.2015.German.C...</a></span><br/><br/>\r\n"
			+ "<span><a href=\"index.php?s=Cinedubs\"><strong class=\"main\">Cinedubs</strong></a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101123\" title=\"Mission.Impossible.Rogue.Nation.2015.German.AC3LD.DL.720p.BluRay.x264-HQX\">Mission.Impossible.Rogue.Nat...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101126\" title=\"Mission.Impossible.Rogue.Nation.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-RELiABLE\">Mission.Impossible.Rogue.Nat...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100974\" title=\"Codename.U.N.C.L.E.German.AC3.Dubbed.1080p.WebHD.h264-PsO\">Codename.U.N.C.L.E.German.AC...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100973\" title=\"Codename.U.N.C.L.E.German.AC3.Dubbed.720p.WebHD.h264-PsO\">Codename.U.N.C.L.E.German.AC...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100971\" title=\"Fantastic.Four.2015.German.DTSD.5.1.DL.1080p.BluRay.x264-DerSchuft\">Fantastic.Four.2015.German.D...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100970\" title=\"Fantastic.Four.2015.German.DTSD.5.1.DL.720p.BluRay.x264-DerSchuft\">Fantastic.Four.2015.German.D...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100890\" title=\"Fantastic.Four.GERMAN.DL.AC3.Dubbed.1080p.BluRay.x264-RELiABLE\">Fantastic.Four.GERMAN.DL.AC3...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100891\" title=\"Fantastic.Four.GERMAN.AC3.Dubbed.720p.BluRay.x264-RELiABLE\">Fantastic.Four.GERMAN.AC3.Du...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100854\" title=\"Hitman.Agent.47.2015.German.MD.DL.1080p.WEBRiP.x264-MULTiPLEX\">Hitman.Agent.47.2015.German....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100855\" title=\"Hitman.Agent.47.2015.German.MD.DL.720p.NEW.WEBRiP.x264-MULTiPLEX\">Hitman.Agent.47.2015.German....</a></span><br/><br/>\r\n"
			+ "<span><a href=\"index.php?s=3D_Cine\"><strong class=\"main\">3D Cinedubs</strong></a></span><br/><br/>\r\n"
			+ "<span><a href=\"index.php?s=XXX\"><strong class=\"main\">XXX</strong></a></span>\r\n"
			+ "<br/><span><a href=\"http://www.hd-area.org/index.php?id=101114\" title=\"UltimateSurrender.15.10.30.Nikki.Darling.And.Nikki.Delano.XXX.720p.MP4-KTR\">UltimateSurrender.15.10.30.N...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101113\" title=\"MommysGirl.15.10.31.Cherie.Deville.And.Jessa.Rhodes.The.Runaway.Part.Two.XXX.1080p.MP4-KTR\">MommysGirl.15.10.31.Cherie.D...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101118\" title=\"BangBros18.15.10.30.Marsha.May.XXX.1080p.MP4-KTR\">BangBros18.15.10.30.Marsha.M...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101117\" title=\"MonsterCurves.15.10.31.Kate.Alton.Sexing.Kate.XXX.1080p.MP4-KTR\">MonsterCurves.15.10.31.Kate....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101116\" title=\"ClubSandy.15.10.31.Elsa.Jean.And.Gina.Valentina.Happy.Halloween.Part.1.XXX.1080p.MP4-KTR\">ClubSandy.15.10.31.Elsa.Jean...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101119\" title=\"PornstarsLikeItBig.15.10.31.Katrina.Jade.Midnight.Titty.Madness.XXX.1080p.MP4-KTR\">PornstarsLikeItBig.15.10.31....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101115\" title=\"AssholeFever.15.10.31.Jessie.Volt.XXX.1080p.MP4-KTR\">AssholeFever.15.10.31.Jessie...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101112\" title=\"GoldenShowerPower.15.03.20.Chelsy.Sun.Leila.Smith.Victoria.Puppy.And.Antonia.Sainz.XXX.1080p.MKV-KTR\">GoldenShowerPower.15.03.20.C...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101111\" title=\"GoldenShowerPower.15.03.03.Adel.Sunshine.Vanessa.And.Kate.Gold.XXX.1080p.MKV-KTR\">GoldenShowerPower.15.03.03.A...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101110\" title=\"Casting.E452.Vicky.XXX.1080p.MOV-KTR\">Casting.E452.Vicky.XXX.1080p...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101108\" title=\"Defloration.15.10.29.Matilda.Oj.Solo.XXX.1080p.MP4-KTR\">Defloration.15.10.29.Matilda...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101107\" title=\"Babes.15.10.31.Alexis.Brill.A.Hump.In.The.Night.XXX.1080p.MP4-KTR\">Babes.15.10.31.Alexis.Brill....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101106\" title=\"ATKGirlfriends.15.10.31.Rachel.James.XXX.1080p.MP4-KTR\">ATKGirlfriends.15.10.31.Rach...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101105\" title=\"21FootArt.15.10.31.Alexis.Brill.XXX.1080p.MP4-KTR\">21FootArt.15.10.31.Alexis.Br...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101104\" title=\"BigTitsAtSchool.15.10.31.Karter.Foxx.Searching.For.Her.Sugar.Pop.XXX.1080p.MP4-KTR\">BigTitsAtSchool.15.10.31.Kar...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101103\" title=\"TeensLoveHugeCocks.15.10.31.Kharlie.Stone.And.Kymberlee.Anna.Pumping.Power.XXX.1080p.MP4-KTR\">TeensLoveHugeCocks.15.10.31....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101102\" title=\"TeensLoveBlackCocks.15.10.30.Nikki.Knightly.XXX.1080p.MP4-KTR\">TeensLoveBlackCocks.15.10.30...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101109\" title=\"Casting.E451.Carla.XXX.1080p.MOV-KTR\">Casting.E451.Carla.XXX.1080p...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101101\" title=\"21EroticAnal.15.10.31.Doris.Ivy.XXX.1080p.MP4-KTR\">21EroticAnal.15.10.31.Doris....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101100\" title=\"PornFidelity.15.10.30.Jodi.Taylor.Nerd.Girls.6.XXX.1080p.MP4-KTR\">PornFidelity.15.10.30.Jodi.T...</a></span><br/></a><br/>\r\n"
			+ "<span><a href=\"index.php?s=3D\"><strong class=\"main\">3D</strong></a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101148\" title=\"300.Rise.Of.An.Empire.3D.2014.MULTi.COMPLETE.BLURAY-SharpHD\">300.Rise.Of.An.Empire.3D.201...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101072\" title=\"Terminator.Genisys.3D.2015.German.DL.1080p.BluRay.x264-STEREOSCOPiC\">Terminator.Genisys.3D.2015.G...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100911\" title=\"Far.Cry.3D.2008.2D3D.MULTi.COMPLETE.BLURAY-SharpHD\">Far.Cry.3D.2008.2D3D.MULTi.C...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100872\" title=\"Die.Schneekoenigin.2.Eiskalt.Entfuehrt.3D.2014.German.DL.1080p.BluRay.x264-ETM\">Die.Schneekoenigin.2.Eiskalt...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100871\" title=\"Zombieworld.3D.2015.MULTi.COMPLETE.BLURAY-GUACAMOLE\">Zombieworld.3D.2015.MULTi.CO...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100863\" title=\"Terminator.Genisys.3D.2015.complete.Bluray.untouched.german.ML.mvc-INd\">Terminator.Genisys.3D.2015.c...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100837\" title=\"Terminator.Genisys.2015.3D.HOU.German.DTSD.DL.1080p.BluRay.x264.READ.NFO-Pate\">Terminator.Genisys.2015.3D.H...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100838\" title=\"Terminator.Genisys.2015.3D.HSBS.German.DTSD.DL.1080p.BluRay.x264.READ.NFO-Pate\">Terminator.Genisys.2015.3D.H...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100800\" title=\"Wasteland.3D.2011.2D3D.MULTi.COMPLETE.BLURAY-SharpHD\">Wasteland.3D.2011.2D3D.MULTi...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=53517\" title=\"Spy.Kids.4.Alle.Zeit.der.Welt.3D.2011.German.DL.1080p.BluRay.x264-MAJESTiC\">Spy.Kids.4.Alle.Zeit.der.Wel...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=54771\" title=\"Dead.Space.Aftermath.3D.2011.German.DL.720p.BluRay.x264-ETM\">Dead.Space.Aftermath.3D.2011...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100669\" title=\"Presidents.Day.3D.2010.2D3D.COMPLETE.BLURAY-SharpHD\">Presidents.Day.3D.2010.2D3D....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=56244\" title=\"Alice.im.Wunderland.3D.2010.German.DL.1080p.BluRay.x264.MerryXmas-ETM\">Alice.im.Wunderland.3D.2010....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100555\" title=\"San.Andreas.3D.2015.DUAL.COMPLETE.BLURAY-ETM\">San.Andreas.3D.2015.DUAL.COM...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100482\" title=\"Every.Thing.Will.Be.Fine.3D.2015.German.DL.1080p.BluRay.x264-MOViEiT\">Every.Thing.Will.Be.Fine.3D....</a></span><br/><br/>\r\n"
			+ "<span><a href=\"index.php?s=Old_Stuff\"><strong class=\"main\">Old_Stuff</strong></a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101135\" title=\"Tinkerbell.2008.German.DTS.DL.1080p.BluRay.x264-OMC\">Tinkerbell.2008.German.DTS.D...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101131\" title=\"Die.Klapperschlange.1981.Remastered.German.DTSD.1080p.US.BD.Remux-marban\">Die.Klapperschlange.1981.Rem...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101130\" title=\"No.Way.Out.1987.German.DL.720p.HDTV.x264-msd\">No.Way.Out.1987.German.DL.72...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100961\" title=\"Soloalbum.Der.Film.2003.German.1080p.BluRay.x264-DETAiLS\">Soloalbum.Der.Film.2003.Germ...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100848\" title=\"Die.Chroniken.von.Narnia.Prinz.Kaspian.von.Narnia.2008.MULTi.COMPLETE.BLURAY-iND\">Die.Chroniken.von.Narnia.Pri...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100798\" title=\"Helene.Fischer.-.Farbenspiel.Live.Die.Stadion.Tournee.2015.COMPLETE.MBLURAY-iND\">Helene.Fischer.-.Farbenspiel...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100794\" title=\"Harry.Potter.und.der.Gefangene.von.Askaban.-.Ultimate.Edition.2004.MULTi.COMPLETE.BLURAY-iND\">Harry.Potter.und.der.Gefange...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100773\" title=\"The.Killing.S03.COMPLETE.DUAL.COMPLETE.BLURAY-iND\">The.Killing.S03.COMPLETE.DUA...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100765\" title=\"Im.Namen.des.Vaters.1993.German.DL.1080p.BluRay.x264-RSG\">Im.Namen.des.Vaters.1993.Ger...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100529\" title=\"Ist.das.Leben.nicht.schoen.1946.German.DL.1080p.BluRay.x264-WOMBAT\">Ist.das.Leben.nicht.schoen.1...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100526\" title=\"Nachtlaerm.German.DL.1080p.BluRay.x264-ETM\">Nachtlaerm.German.DL.1080p.B...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100525\" title=\"Nachtlaerm.German.DL.720p.BluRay.x264-ETM\">Nachtlaerm.German.DL.720p.Bl...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100456\" title=\"Autumn.in.New.York.Es.begann.im.September.2000.German.AC3D.DL.720p.BluRay.x264-msd\">Autumn.in.New.York.Es.begann...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100455\" title=\"National.Geographic.Die.Entstehung.Europas.2004.DOKU.DUAL.COMPLETE.BLURAY-iND\">National.Geographic.Die.Ents...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=100457\" title=\"Bound.Gefesselt.1996.German.AC3D.DL.1080p.BluRay.x264-KLASSiGERHD\">Bound.Gefesselt.1996.German....</a></span><br/><br/>\r\n"
			+ "<span><a href=\"index.php?s=Musik\"><strong class=\"main\">Musik</strong></a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=99210\" title=\"Mussorgsky.Bilder.einer.Ausstellung.SACD.FLAC.2.0_5.0\">Mussorgsky.Bilder.einer.Auss...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=99184\" title=\"Yes.-.The.Yes.Album.Bluray-Audio\">Yes.-.The.Yes.Album.Bluray-A...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=99183\" title=\"Carlos.Heredia.Gypsy.Flamenco.SACD.2.0+5.0\">Carlos.Heredia.Gypsy.Flamenc...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=98903\" title=\"SPES.2014.complete.Bluray.untouched.AVC.Auro.3D.9.1-HDC\">SPES.2014.complete.Bluray.un...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=92896\" title=\"Carlos.Santana.Collection.1969-2014.71.ALBUMS.FLAC\">Carlos.Santana.Collection.19...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=87882\" title=\"Pink.Floyd.The.Endless.River.2014.complete.Bluray.untouched-HDA\">Pink.Floyd.The.Endless.River...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=84035\" title=\"The.Hyperion.Romantic.Piano.Concerto.series.01-42\">The.Hyperion.Romantic.Piano....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=71634\" title=\"Putumayo.113.CD.Flac.lossless.Music-HDArea\">Putumayo.113.CD.Flac.lossles...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=71445\" title=\"UFO – Let It Roll (Limited Edition 4CD Box Set) – 2010 FLAC\">UFO – Let It Roll (Limited...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=48475\" title=\"Foo Fighters - Everywhere But Home (2003) [DVD]\">Foo Fighters - Everywhere Bu...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=48371\" title=\"Distant Worlds - Music From Final Fantasy (Returning Home) (2011) [DVD9]\">Distant Worlds - Music From ...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=47088\" title=\"Koda Kumi - Live Tour 2011 ~Dejavu~ (2012) [2xDVD9]\">Koda Kumi - Live Tour 2011 ~...</a></span><br/><br/>\r\n"
			+ "<span><a href=\"index.php?s=movies\"><strong class=\"main\">Filme</strong></a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=97886\" title=\"Graceland.S02.GERMAN.Dubbed.720p.WebHD.h264-idTV\">Graceland.S02.GERMAN.Dubbed....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=98443\" title=\"Hannibal.S03.German.Dubbed.720p.HDTV.x264-CRiSP\">Hannibal.S03.German.Dubbed.7...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=98444\" title=\"Hannibal.S03.GERMAN.DUBBED.DL.1080p.WebHD.x264-TVP\">Hannibal.S03.GERMAN.DUBBED.D...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=97990\" title=\"Star.Wars.Rebels.S02.GERMAN.DUBBED.720p.WebHD.x264-TVP\">Star.Wars.Rebels.S02.GERMAN....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101167\" title=\"Die.Morde.von.Snowtown.2011.German.DL.1080p.BluRay.x264-ENCOUNTERS\">Die.Morde.von.Snowtown.2011....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101163\" title=\"Power.Rangers.Super.Samurai.S01.DiSC1+2.2012.DUAL.COMPLETE.BLURAY-iFPD\">Power.Rangers.Super.Samurai....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101166\" title=\"Aegypten.Das.Raetsel.um.Grab.33.GERMAN.DOKU.WS.720p.HDTV.x264-OWG\">Aegypten.Das.Raetsel.um.Grab...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101165\" title=\"Rettet.Nemo.GERMAN.DOKU.720p.HDTV.x264-iQ\">Rettet.Nemo.GERMAN.DOKU.720p...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101164\" title=\"Die.Geschichte.der.Modernen.Zivilisation.Complete.GERMAN.DOKU.720p.HDTV.x264-MDGP\">Die.Geschichte.der.Modernen....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101146\" title=\"Dealer.Trip.in.die.Hoelle.2014.German.DTS.1080p.BluRay.x264-KOC\">Dealer.Trip.in.die.Hoelle.20...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=37535\" title=\"Die.Herrschaft.der.Schatten.German.DL.1080p.BluRay.x264-BRiGHT\">Die.Herrschaft.der.Schatten....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101162\" title=\"Die.Meute.UNCUT.2010.German.DTS.1080p.BluRay.x264-SoW \">Die.Meute.UNCUT.2010.German....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101161\" title=\"Die.Horde.Uncut.2009.German.DTS.1080p.BluRay.x264-RSG \">Die.Horde.Uncut.2009.German....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=88001\" title=\"Romeo.must.die.2000.German.DL.1080p.BluRay.x264-DETAiLS\">Romeo.must.die.2000.German.D...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101159\" title=\"Maigret.kennt.kein.Erbarmen.1959.German.1080p.BluRay.x264-iFPD\">Maigret.kennt.kein.Erbarmen....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101160\" title=\"Maigret.kennt.kein.Erbarmen.1959.German.720p.BluRay.x264-iFPD\">Maigret.kennt.kein.Erbarmen....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101158\" title=\"Leon.der.Profi.1994.German.DL.720p.BluRay.x264.iNTERNAL-VideoStar\">Leon.der.Profi.1994.German.D...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101157\" title=\"Buddy.haut.den.Lukas.1980.GERMAN.COMPLETE.BLURAY-iFPD\">Buddy.haut.den.Lukas.1980.GE...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101156\" title=\"Mama.Muh.Die.neuen.Abenteuer.S01.DiSC1.2009.DUAL.COMPLETE.BLURAY-iFPD\">Mama.Muh.Die.neuen.Abenteuer...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101152\" title=\"Chingachgook.die.grosse.Schlange.1967.GERMAN.COMPLETE.BLURAY-iFPD\">Chingachgook.die.grosse.Schl...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101149\" title=\"Demonic.2015.MULTi.COMPLETE.BLURAY-BDA\">Demonic.2015.MULTi.COMPLETE....</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101153\" title=\"Wunden.der.Angst.2014.German.DL.1080p.BluRay.x264-ENCOUNTERS\">Wunden.der.Angst.2014.German...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101154\" title=\"Wunden.der.Angst.2014.German.720p.BluRay.x264-ENCOUNTERS\">Wunden.der.Angst.2014.German...</a></span><br/><span><a href=\"http://www.hd-area.org/index.php?id=101150\" title=\"Osceola.1971.GERMAN.COMPLETE.BLURAY-iFPD\">Osceola.1971.GERMAN.COMPLETE...</a></span><br/><br/>\r\n"
			+ "</div>\r\n" + " \r\n" + "<div id=\"rss\">&nbsp;</div>\r\n" + "<div class=\"rightbox\">\r\n"
			+ "<a href=\"http://www.hd-area.org/?s=feedrss\" target=\"blank\">RSS Feed anzeigen</a>\r\n" + "<br/>\r\n"
			+ "<a href=\"http://www.hd-area.org/?s=feedrss\" target=\"blank\">Atom Feed anzeigen</a></div>\r\n"
			+ " \r\n" + "<div class=\"subbottom\">&nbsp;</div>\r\n" + "</div>\r\n" + " \r\n" + " \r\n" + " \r\n"
			+ "<div id=\"content\">\r\n" + " \r\n" + " \r\n" + " \r\n" + "<div class=\"topbox\">\r\n" + " \r\n"
			+ "<div class=\"boxlinks\">\r\n" + "<div id=\"title\" class=\"title\">\r\n"
			+ "<a href=\"http://www.hd-area.org/index.php?id=92334\" title=\"How.to.Get.Away.with.Murder.S01.GERMAN.720p.HDTV.x264-MDGP\"><nobr>\r\n"
			+ "<h1>How.to.Get.Away.with.Murder.S01.GERMAN.720p.HDTV.x264-MDGP...</h1></nobr></a></div>\r\n"
			+ "<div class=\"topinfo title\">Uploader: <b>HDA</b> • Datum: <b>22.07.15</b> • Kategorie <a href=\"http://www.hd-area.org/index.php?s=movies&amp;c=720p\">720p</a> > <a href=\"http://www.hd-area.org/index.php?s=movies&amp;c=Serien\">Serien</a>\r\n"
			+ "</div></div>\r\n" + " \r\n" + " \r\n" + "<div class=\"boxrechts\">\r\n"
			+ "<a href=\"http://anonym.to/?http://www.imdb.com/title/tt3205802/\"target=\"_blank\" rel=\"nofollow\" title=\"How.to.Get.Away.with.Murder.S01.GERMAN.720p.HDTV.x264-MDGP\">IMDb 8,3/10</a>\r\n"
			+ "\r\n" + "</div></div>\r\n" + "<!-- Boxheader Rechts Ende -->\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "<div class=\"download\">\r\n" + "\r\n" + "<!-- Cover  -->\r\n"
			+ "<div class=\"cover\" style=\"text-align: left\">\r\n" + "\r\n"
			+ "<a href=\"http://e-pic.biz/img/O12z4c6AhgeMnIG.jpg\" target=\"_blank\" alt=\"How.to.Get.Away.with.Murder.S01.GERMAN.720p.HDTV.x264-MDGP\">\r\n"
			+ "<img style=\"border: 0pt none ; float: left; margin-right: 15px; width: 200px;\" alt=\"How.to.Get.Away.with.Murder.S01.GERMAN.720p.HDTV.x264-MDGP\" src=\"http://e-pic.biz/img/O12z4c6AhgeMnIG.jpg\"/>\r\n"
			+ "</a>\r\n" + "<!-- Cover Ende -->\r\n" + "\r\n" + "\r\n" + "<!-- Download Info -->\r\n"
			+ "<div class=\"beschreibung\">\r\n" + "\r\n" + "<!-- Jahr -->\r\n" + "\r\n"
			+ "<strong class=\"main\">Jahr:</strong> \r\n" + "2014<br />\r\n" + "\r\n" + "<!-- Jahr Ende -->\r\n"
			+ "\r\n" + "\r\n" + "<!-- Genre -->\r\n" + "\r\n" + "<strong class=\"main\">Genre:</strong> \r\n"
			+ "Krimi | Drama | Mystery<br />\r\n" + "\r\n" + "<!-- Genre Ende -->\r\n" + "\r\n" + "\r\n"
			+ "<!-- Sprache -->\r\n" + "\r\n" + "<strong class=\"main\">Sprache:</strong> \r\n"
			+ "Deutsch AC3<br />\r\n" + "\r\n" + "<!-- Sprache Ende -->\r\n" + "\r\n" + "<!-- Länge -->\r\n" + "\r\n"
			+ "<strong class=\"main\">Laufzeit:</strong> \r\n" + "41min je Folge<br />\r\n" + "\r\n"
			+ "<!-- Länge Ende -->\r\n" + "\r\n" + "\r\n" + "<!-- Bitrate -->\r\n" + "\r\n"
			+ "<strong class=\"main\">Bitrate:</strong> \r\n" + "2000 Kbps<br />\r\n" + "\r\n"
			+ "<!-- Bitrate Ende -->\r\n" + "\r\n" + "\r\n" + "<!-- Format -->\r\n" + "\r\n"
			+ "<strong class=\"main\">Format:</strong> \r\n" + "MKV<br />\r\n" + "\r\n" + "<!-- Format Ende -->\r\n"
			+ "\r\n" + "<!-- Größe -->\r\n" + "\r\n" + "<strong class=\"main\">Größe:</strong> \r\n"
			+ "750 MB je Folge<br />\r\n" + "\r\n" + "<!-- Größe Ende -->\r\n" + "\r\n" + "<!-- Release Name -->\r\n"
			+ "<strong class=\"main\">Release:</strong> <input type=\"text\" onclick=\"this.focus();this.select();\" value=\"How.to.Get.Away.with.Murder.S01.GERMAN.720p.HDTV.x264-MDGP\" style=\"background-color: rgb(255, 255, 255); width: 250px;\" class=\"inputbox\"/><br /><br />\r\n"
			+ "<!-- Release Name Ende -->\r\n" + "<!-- Story -->\r\n"
			+ "<strong class=\"main\">Beschreibung:</strong><br /><span class=\"sub\"><p>Oscargewinnerin Viola Davis spielt in der US-Serie &bdquo;How to Get Away  with Murder&ldquo; die Hauptrolle einer brillanten, aber mysteri&ouml;sen  Professorin f&uuml;r Strafrecht, Annalise Keating. Diese ist nebenbei als  Strafverteidigerin t&auml;tig. Sie ist sowohl im H&ouml;r- als auch im  Gerichtssaal charismatisch, passioniert &ndash; und auch gnadenlos. Sie wei&szlig;,  wie man Menschen effektiv manipuliert und wendet dieses K&ouml;nnen auch oft  bei ihren Studenten an. Einige davon hat sie sogar ausgew&auml;hlt, ihr bei  ihrer Arbeit am Gericht behilflich zu sein:</p>\r\n"
			+ "<p>Darunter ist der junge Wes Gibbins (Alfred Enoch), der sich als  Kandidat von der Warteliste unter seinen Kommilitonen besonders beweisen  muss. Die Arbeit f&uuml;r Professor Keating ist eine gro&szlig;e Chance f&uuml;r ihn.  Doch wird das Geheimnis, das er unfreiwillig mit ihr teilt ihm schaden?</p>\r\n"
			+ "<p>&nbsp;</p>\r\n" + "<p><strong>enthaltene Folgen:</strong></p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E01.Das.beste.Team.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E02.Mord.mal.2.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E03.Aufs.Kreuz.gelegt.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E04.Insiderwissen.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E05.Nackte.Tatsachen.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E06.Kampfansage.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E07.Manipulation.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E08.Kein.Weg.zurueck.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E09.Kill.Me.Kill.Me.Kill.Me.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E10.Unter.Druck.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E11.Nichts.bleibt.verborgen.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E12.Schuldig.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E13.Strippenzieher.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E14.In.flagranti.GERMAN.720p.HDTV.x264-MDGP</p>\r\n"
			+ "<p>How.to.Get.Away.with.Murder.S01E15.Nichts.als.die.Wahrheit.GERMAN.720p.HDTV.x264-MDGP <strong>NEU</strong></p></span><br /><br /><div align=\"left\"><p><strong>General</strong><br />Complete name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : How.to.Get.Away.with.Murder.S01E01.Das.beste.Team.GERMAN.720p.HDTV.x264-MDGP\\mdgp-howtogets01e01-720p.mkv<br />Format&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Matroska<br />Format version&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Version 4 / Version 2<br />File size&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 725 MiB<br />Duration&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 41mn 38s<br />Overall bit rate&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 2 434 Kbps<br />Encoded date&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : UTC 2015-04-16 08:30:47<br />Writing application&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : mkvmerge v7.6.0 ('Garden of Dreams') 64bit built on Feb&nbsp; 8 2015 13:04:34<br />Writing library&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : libebml v1.3.1 + libmatroska v1.4.2<br />DURATION&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 00:41:38.080000000<br />NUMBER_OF_FRAMES&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 78065<br />NUMBER_OF_BYTES&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 119907840<br />_STATISTICS_WRITING_APP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : mkvmerge v7.6.0 ('Garden of Dreams') 64bit built on Feb&nbsp; 8 2015 13:04:34<br />_STATISTICS_WRITING_DATE_UTC&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 2015-04-16 08:30:47<br />_STATISTICS_TAGS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES<br /><br /><strong>Video</strong><br />ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 1<br />Format&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : AVC<br />Format/Info&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Advanced Video Codec<br />Format profile&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : High@L4.1<br />Format settings, CABAC&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Yes<br />Format settings, ReFrames&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 5 frames<br />Codec ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : V_MPEG4/ISO/AVC<br />Duration&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 41mn 38s<br />Bit rate&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 2 002 Kbps<br />Width&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 1 280 pixels<br />Height&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 720 pixels<br />Display aspect ratio&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 16:9<br />Frame rate mode&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Constant<br />Frame rate&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 25.000 fps<br />Color space&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : YUV<br />Chroma subsampling&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 4:2:0<br />Bit depth&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 8 bits<br />Scan type&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Progressive<br />Bits/(Pixel*Frame)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 0.087<br />Stream size&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 596 MiB (82%)<br />Writing library&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : x264 core 146 r2538 121396c<br />Encoding settings&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : cabac=1 / ref=5 / deblock=1:-3:-3 / analyse=0x3:0x113 / me=umh / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=20.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00<br />Language&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : German<br />Default&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Yes<br />Forced&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : No<br />Color primaries&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : BT.709<br />Transfer characteristics&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : BT.709<br />Matrix coefficients&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : BT.709<br /><br /><strong>Audio</strong><br />ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 2<br />Format&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : AC-3<br />Format/Info&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Audio Coding 3<br />Mode extension&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : CM (complete main)<br />Format settings, Endianness&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Big<br />Codec ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : A_AC3<br />Duration&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 41mn 38s<br />Bit rate mode&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Constant<br />Bit rate&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 384 Kbps<br />Channel(s)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 2 channels<br />Channel positions&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Front: L R<br />Sampling rate&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 48.0 KHz<br />Bit depth&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 16 bits<br />Compression mode&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Lossy<br />Stream size&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : 114 MiB (16%)<br />Language&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : German<br />Default&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : Yes<br />Forced&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : No<br /><br /></p><br /><br />\r\n"
			+ "<!-- Story Ende -->\r\n" + "\r\n" + "\r\n" + "\r\n" + "<!-- Screenshots -->\r\n" + "\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "<!-- Hoster -->\r\n" + "<strong class=\"main\">Download:</strong><br/>\r\n"
			+ "<span style='display:none;'><a href=\"&#x68;&#x74;&#x74;&#x70;&#x3a;&#x2f;&#x2f;&#x73;&#x68;&#x61;&#x72;&#x65;&#x2d;&#x6c;&#x69;&#x6e;&#x6b;&#x73;&#x2e;&#x62;&#x69;&#x7a;&#x2f;&#x5f;&#x77;&#x74;&#x70;&#x6c;&#x75;&#x6f;&#x6c;&#x64;&#x77;&#x74;&#x61;&#x35;\" target=\"_blank\">Share-Online.biz</a></span><span style='display:inline;'><a href=\"&#x68;&#x74;&#x74;&#x70;&#x3a;&#x2f;&#x2f;&#x73;&#x68;&#x61;&#x72;&#x65;&#x2d;&#x6c;&#x69;&#x6e;&#x6b;&#x73;&#x2e;&#x62;&#x69;&#x7a;&#x2f;&#x5f;&#x64;&#x38;&#x70;&#x6c;&#x75;&#x6f;&#x6c;&#x63;&#x73;&#x73;&#x6f;&#x78;&#x69;\" target=\"_blank\">&#x20;&#x20;</a></span><span style='display:none;'><a href=\"&#x68;&#x74;&#x74;&#x70;&#x3a;&#x2f;&#x2f;&#x73;&#x68;&#x61;&#x72;&#x65;&#x2d;&#x6c;&#x69;&#x6e;&#x6b;&#x73;&#x2e;&#x62;&#x69;&#x7a;&#x2f;&#x5f;&#x30;&#x38;&#x70;&#x6c;&#x75;&#x6f;&#x6c;&#x6f;&#x38;&#x76;&#x65;\" target=\"_blank\">Share-Online.biz</a></span><span style='display:inline;'><a href=\"&#x68;&#x74;&#x74;&#x70;&#x3a;&#x2f;&#x2f;&#x66;&#x69;&#x6c;&#x65;&#x63;&#x72;&#x79;&#x70;&#x74;&#x2e;&#x63;&#x63;&#x2f;&#x43;&#x6f;&#x6e;&#x74;&#x61;&#x69;&#x6e;&#x65;&#x72;&#x2f;&#x45;&#x30;&#x39;&#x36;&#x30;&#x33;&#x45;&#x30;&#x42;&#x35;&#x2e;&#x68;&#x74;&#x6d;&#x6c;\" target=\"_blank\">Share-Online.biz</a></span><span style='display:none;'><a href=\"&#x68;&#x74;&#x74;&#x70;&#x3a;&#x2f;&#x2f;&#x73;&#x68;&#x61;&#x72;&#x65;&#x2d;&#x6c;&#x69;&#x6e;&#x6b;&#x73;&#x2e;&#x62;&#x69;&#x7a;&#x2f;&#x5f;&#x63;&#x6e;&#x6f;&#x6c;&#x75;&#x6f;&#x6c;&#x35;&#x6b;&#x71;&#x32;&#x70;&#x32;\" target=\"_blank\">Share-Online.biz</a></span>\r\n"
			+ " | <span style='display:none;'><a href=\"&#x68;&#x74;&#x74;&#x70;&#x3a;&#x2f;&#x2f;&#x73;&#x68;&#x61;&#x72;&#x65;&#x2d;&#x6c;&#x69;&#x6e;&#x6b;&#x73;&#x2e;&#x62;&#x69;&#x7a;&#x2f;&#x5f;&#x7a;&#x79;&#x6f;&#x6c;&#x75;&#x6f;&#x6c;&#x39;&#x76;&#x33;&#x67;&#x62;\" target=\"_blank\">Uploaded.net</a></span><span style='display:inline;'><a href=\"&#x68;&#x74;&#x74;&#x70;&#x3a;&#x2f;&#x2f;&#x73;&#x68;&#x61;&#x72;&#x65;&#x2d;&#x6c;&#x69;&#x6e;&#x6b;&#x73;&#x2e;&#x62;&#x69;&#x7a;&#x2f;&#x5f;&#x78;&#x73;&#x70;&#x6c;&#x75;&#x6f;&#x6c;&#x62;&#x6a;&#x7a;&#x68;&#x79;\" target=\"_blank\">&#x20;&#x20;</a></span><span style='display:none;'><a href=\"&#x68;&#x74;&#x74;&#x70;&#x3a;&#x2f;&#x2f;&#x73;&#x68;&#x61;&#x72;&#x65;&#x2d;&#x6c;&#x69;&#x6e;&#x6b;&#x73;&#x2e;&#x62;&#x69;&#x7a;&#x2f;&#x5f;&#x7a;&#x79;&#x6f;&#x6c;&#x75;&#x6f;&#x6c;&#x39;&#x76;&#x33;&#x67;&#x62;\" target=\"_blank\">Uploaded.net</a></span><span style='display:inline;'><a href=\"&#x68;&#x74;&#x74;&#x70;&#x3a;&#x2f;&#x2f;&#x66;&#x69;&#x6c;&#x65;&#x63;&#x72;&#x79;&#x70;&#x74;&#x2e;&#x63;&#x63;&#x2f;&#x43;&#x6f;&#x6e;&#x74;&#x61;&#x69;&#x6e;&#x65;&#x72;&#x2f;&#x32;&#x36;&#x39;&#x35;&#x46;&#x37;&#x45;&#x41;&#x32;&#x31;&#x2e;&#x68;&#x74;&#x6d;&#x6c;\" target=\"_blank\">Uploaded.net</a></span><span style='display:none;'><a href=\"&#x68;&#x74;&#x74;&#x70;&#x3a;&#x2f;&#x2f;&#x73;&#x68;&#x61;&#x72;&#x65;&#x2d;&#x6c;&#x69;&#x6e;&#x6b;&#x73;&#x2e;&#x62;&#x69;&#x7a;&#x2f;&#x5f;&#x7a;&#x79;&#x6f;&#x6c;&#x75;&#x6f;&#x6c;&#x39;&#x76;&#x33;&#x67;&#x62;\" target=\"_blank\">Uploaded.net</a></span>\r\n"
			+ "<!-- Hoster Ende -->\r\n" + "\r\n" + "</div></div>\r\n" + "<!-- Download Info Ende -->\r\n"
			+ "</div></div>\r\n" + "<!-- Box Unten -->\r\n" + "<div class=\"dlbottom\">\r\n"
			+ " <a href=\"javascript:history.back();\">Zurück</a>\r\n" + "\r\n" + "</div>\r\n"
			+ "<!-- Box Unten Ende -->\r\n" + "\r\n" + "\r\n"
			+ "<div id=\"topkommentare\">&nbsp;</div><div id=\"kommentare\"><h3 id=\"Kommentar\"><a href=\"http://www.hd-area.org/index.php?id=92334#Kommentar\"  class=\"comments_invite\">Kommentare</a></h3>\r\n"
			+ "\r\n" + "\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "<form id=\"txpCommentInputForm\" method=\"post\" action=\"/index.php?id=92334#cpreview\">\r\n"
			+ "<div class=\"comments-wrapper\">\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "<table cellpadding=\"4\" cellspacing=\"0\" border=\"0\">\r\n" + "\r\n" + "<tr>\r\n"
			+ "	<td align=\"right\">\r\n" + "		<label for=\"name\">Name</label>\r\n" + "	</td>\r\n" + "\r\n"
			+ "	<td>\r\n"
			+ "		<input type=\"text\" value=\"\" name=\"name\" size=\"25\" class=\"comment_name_input\" id=\"name\" />\r\n"
			+ "	</td>\r\n" + "\r\n" + "	<td>\r\n"
			+ "		<input type=\"checkbox\" name=\"remember\" value=\"1\" id=\"remember\" checked=\"checked\" class=\"checkbox active\" /> <label for=\"remember\">Merken</label> <input type=\"hidden\" value=\"remember\" name=\"checkbox_type\" />\r\n"
			+ "	</td> \r\n" + "</tr>\r\n" + "\r\n" + "<tr>\r\n" + "	<td align=\"right\">\r\n"
			+ "		<label for=\"email\">E-Mail</label>\r\n" + "	</td>\r\n" + "\r\n" + "	<td colspan=\"2\">\r\n"
			+ "		<input type=\"text\" value=\"\" name=\"email\" size=\"25\" class=\"comment_email_input\" id=\"email\" />\r\n"
			+ "	</td>\r\n" + "</tr>\r\n" + "\r\n" + "<tr> \r\n" + "	<td align=\"right\">\r\n"
			+ "		<label for=\"web\">Web</label>\r\n" + "	</td>\r\n" + "\r\n" + "	<td colspan=\"2\">\r\n"
			+ "		<input type=\"text\" value=\"\" name=\"web\" size=\"25\" class=\"comment_web_input\" id=\"web\" />\r\n"
			+ "	</td>\r\n" + "</tr>\r\n" + "\r\n" + "<tr>\r\n" + "	<td align=\"right\">\r\n"
			+ "		<label for=\"message\">Nachricht</label>\r\n" + "	</td>\r\n" + "\r\n" + "	<td colspan=\"2\">\r\n"
			+ "		<textarea id=\"message\" name=\"message\" cols=\"45\" rows=\"15\" class=\"txpCommentInputMessage\"></textarea>\r\n"
			+ "	</td>\r\n" + "</tr>\r\n" + "\r\n" + "<tr>\r\n" + "	<td>&nbsp;</td>\r\n" + "	<td align=\"left\">\r\n"
			+ "		<input type=\"submit\" value=\"Vorschau\" name=\"preview\" class=\"button\" id=\"txpCommentPreview\" />\r\n"
			+ "		<input type=\"submit\" value=\"Absenden\" name=\"submit\" class=\"button disabled\" id=\"txpCommentSubmit\" disabled=\"disabled\" />\r\n"
			+ "	</td>\r\n" + "<td  align=\"right\">\r\n" + "	</td>\r\n" + "</tr>\r\n" + "\r\n" + "</table>\r\n"
			+ "\r\n" + "<input type=\"hidden\" value=\"92334\" name=\"parentid\" />\r\n"
			+ "<input type=\"hidden\" value=\"/index.php?id=92334\" name=\"backpage\" />\r\n" + "\r\n" + "</div>\r\n"
			+ "</form>\r\n" + "</div><div id=\"bottomline\">&nbsp;</div>\r\n" + "\r\n" + "\r\n"
			+ "<!-- Downloads Ende -->\r\n" + "</div>\r\n" + "<!-- Content Ende -->\r\n"
			+ "<!-- Seitenzahl unten-->\r\n" + "<div class=\"navizahl\" id=\"navizahl\">\r\n" + "<center>\r\n"
			+ "<txp:rsx_page_number_list nav=\"1\" leftward=\"[&lt;&lt; Prev]\" rightward=\"[Next &gt;&gt;]\" delim=\" \" windowsize=\"10\" />\r\n"
			+ "</center>\r\n" + "</div>\r\n" + "</div>\r\n" + "<!-- Container Ende -->\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "<!-- Footer -->\r\n" + "<div id=\"footer\">\r\n"
			+ "<p>&copy; 2008-2015 <a href=\"http://www.hd-area.org/\" title=\"HD-Area.org\">HD-Area.org</a> • Design by <a href=\"mailto:haschtencuerden@gulli.com\">haschtencuerden</a></p>\r\n"
			+ "<center>Page generiert am: 01.11.2015, 19:12:55</center>\r\n" + "<br/><br/>\r\n"
			+ "<div style=\"text-align:center\">\r\n" + "\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n" + "</body>\r\n"
			+ "</html>";

	@Test(expected = IllegalArgumentException.class)
	public void parseHdaWebsiteStringToHdaEntryTestWrongWebsite() {
		final String website = "http://www.google.de";
		HdaEntryParser.parseHdaWebsiteStringToHdaEntry(website);
	}

	@Test
	public void isContentEmpty() {
		final HdaEntry hdaEntry = new HdaEntry();
		HdaEntryParser.setContent(hdaEntry, Jsoup.parse(testWebSite));
		assertThat(hdaEntry.getContent()).isNotEmpty();
	}

	@Test
	public void isLinkSize10() {
		final HdaEntry hdaEntry = new HdaEntry();
		HdaEntryParser.setLinks(hdaEntry, Jsoup.parse(testWebSite));
		// anzahl der Links
		assertThat(hdaEntry.getListHdaLinks().size()).isEqualTo(10);
	}

	//
	// @Test(expected = IllegalArgumentException.class)
	// public void parseHdaWebsiteStringToHdaEntryTestWrongWebsite2() {
	// final String website = "http://www.hd-area.org/index.php?id=92334";
	// HdaEntryParser.parseHdaWebsiteStringToHdaEntry(website);
	// }
}
